version: '3.7'

services:
  image-server:
    image: harbor.eengine.pl/base/php8.0
    entrypoint: docker-entrypoint-override
    ports:
      - "81:80"
    environment:
      - WEB_ROOT=/app/public
    volumes:
      - .:/app
      - ./apache2.conf:/etc/apache2/apache2.conf
      - ./docker-entrypoint-override.sh:/usr/local/bin/docker-entrypoint-override
